version: '2'
services:
  app:
    image: gradle:jdk8
    environment:
    - DEBUG=true
    - CONFIG=production
    - "ES_JAVA_OPTS=-Xms25g -Xmx25g"
    volumes:
      - .:/opt/app
    ulimits:
      memlock:
        soft: -1
        hard: -1
    working_dir: /opt/app
    entrypoint: ./gradlew run
